name: scada
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8

  # IMPORTANTE: Si en tu main.dart agregaste el Chatbot con IA o gráficas,
  # quítale el símbolo '#' a las siguientes líneas según lo que necesites:
  # http: ^1.2.0
  # fl_chart: ^0.65.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true 

  # AQUÍ ESTÁ LA CORRECCIÓN DE LA IMAGEN CON LOS ESPACIOS EXACTOS:
  #assets:
    #- assets/maquina_scada.png