// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvlYuKO1fs22rux5UKXSZ9JLeSOeRnLjQ',
    appId: '1:926265125632:web:476bfc5d24c8c94430e1e5',
    messagingSenderId: '926265125632',
    projectId: 'project-react-ceea5',
    authDomain: 'project-react-ceea5.firebaseapp.com',
    storageBucket: 'project-react-ceea5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJZ-6f5CyQoX18SzwDbuasvJZUa7Tecao',
    appId: '1:926265125632:android:039f96d1773c067730e1e5',
    messagingSenderId: '926265125632',
    projectId: 'project-react-ceea5',
    storageBucket: 'project-react-ceea5.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvlYuKO1fs22rux5UKXSZ9JLeSOeRnLjQ',
    appId: '1:926265125632:web:0761caf48e008cd830e1e5',
    messagingSenderId: '926265125632',
    projectId: 'project-react-ceea5',
    authDomain: 'project-react-ceea5.firebaseapp.com',
    storageBucket: 'project-react-ceea5.firebasestorage.app',
  );

}