// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNeKCE_iTHSJPlGMUlbvOOlYjRNg80q_I',
    appId: '1:1012343664574:web:87b45a6e9c0398183213ef',
    messagingSenderId: '1012343664574',
    projectId: 'proyecto-react-f542f',
    authDomain: 'proyecto-react-f542f.firebaseapp.com',
    storageBucket: 'proyecto-react-f542f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAimUEJosCvdGTsvB2TREiMm4alerQBa4',
    appId: '1:1012343664574:android:706b6418b34dd5953213ef',
    messagingSenderId: '1012343664574',
    projectId: 'proyecto-react-f542f',
    storageBucket: 'proyecto-react-f542f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ-0RLO6uD10KFTEKp2NUXsppa0ztv0O8',
    appId: '1:1012343664574:ios:2736425779b192f33213ef',
    messagingSenderId: '1012343664574',
    projectId: 'proyecto-react-f542f',
    storageBucket: 'proyecto-react-f542f.firebasestorage.app',
    iosBundleId: 'yes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ-0RLO6uD10KFTEKp2NUXsppa0ztv0O8',
    appId: '1:1012343664574:ios:e549d64f66b90cc03213ef',
    messagingSenderId: '1012343664574',
    projectId: 'proyecto-react-f542f',
    storageBucket: 'proyecto-react-f542f.firebasestorage.app',
    iosBundleId: 'no',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNeKCE_iTHSJPlGMUlbvOOlYjRNg80q_I',
    appId: '1:1012343664574:web:c2983363504535243213ef',
    messagingSenderId: '1012343664574',
    projectId: 'proyecto-react-f542f',
    authDomain: 'proyecto-react-f542f.firebaseapp.com',
    storageBucket: 'proyecto-react-f542f.firebasestorage.app',
  );
}
